### PR TITLE
9999407-java-duplicate-code-exact-fixer

### PR DESCRIPTION
**Pull request by codefix-service-user**
62420488-668Java fixer to fix duplicate code exact<br/>CAP issue id: 62420488-668

### CODE REVIEW

**Comment by ganapathy-df** [comment]
https://devgraph-alp.atlassian.net/browse/CC-139644
Automated QE Check Result: FAILED
ValidateAllDuplicateLinesAreExactlyTheSame: FAILED 
<pre>Expression did not match in other instance for (DomElement element : configPage.getElementsByTagName("input")) {
    if ("hidden".equals(element.getAttribute("type")) && element.getAttribute("class").contains("complex-password-field")) {
        final HtmlHiddenInput input = (HtmlHiddenInput) element;
        assertTrue(input.getValueAttribute().startsWith("{"));
        assertTrue(input.getValueAttribute().endsWith("}"));
    }
}</pre>
ValidateDuplicateCodeIsEqualOrMoreThanMinimumDuplicateLines: SUCCESS 
ValidateDuplicateCodeStartLineIsCorrect: SUCCESS 
ValidateDuplicateCodeEndLineIsCorrect: SUCCESS 
ValidateThatDuplicateCodeShouldBeExtracted: SUCCESS 
ValidateOnlyRemovedLinesAreAddedIntoExtractedCodeWithSomeExceptions: SUCCESS 
ValidateAddedCodeHasCorrectAccessModifier: SUCCESS 
ValidateThatCallToExtractedMethodIsSameAtAllPlaces: FAILED 
<pre>Call to extracted method are not the same at all places: 
extractedMethod86986(configPage); // CAP AL
extractedMethod86986(htmlPage); // CAP AL</pre>
ValidateImportsAreCorrect: SUCCESS 
ValidateExtractedMethodIsInCorrectLocation: SUCCESS 
ValidateFilesModifiedInPrMatchesTheFileInJira: SUCCESS 
ValidateMethodParameterOnExtractedCodeIsProperlyUsed - : SUCCESS 
<pre>Parameters: configPage</pre>
ValidateMethodParameterAndArgumentsAreSame: SUCCESS 
ValidateThatDeletedLinesMatchesTheDuplicateCodesInJira: SUCCESS 
validateHandlingOfVariableAssignmentIsCorrect: FAILED 
<pre>Variable element is not updated
Variable element is not updated
Variable element is not updated
</pre>
ValidateThatAllDeletedLinesAreTheSameAtAllPlaces: FAILED 
<pre>Number of deleted lines are not the same on all instances</pre>
ValidateAddedCodeAreRelatedToDuplicateCodeFixing: SUCCESS 
ValidateVariablesUsedInsideExtractedCodeAreAccessible: SUCCESS 
ValidateMethodCanBeStatic: SUCCESS

**Comment by ganapathy-df** [comment]
Valid fix

**Comment by audalykh** [comment]
https://devgraph-alp.atlassian.net/browse/CC-139644
Automated QE Check Result: FAILED
ValidateAllDuplicateLinesAreExactlyTheSame: FAILED 
<pre>Expression did not match in other instance for (DomElement element : configPage.getElementsByTagName("input")) {
    if ("hidden".equals(element.getAttribute("type")) && element.getAttribute("class").contains("complex-password-field")) {
        final HtmlHiddenInput input = (HtmlHiddenInput) element;
        assertTrue(input.getValueAttribute().startsWith("{"));
        assertTrue(input.getValueAttribute().endsWith("}"));
    }
}</pre>
ValidateDuplicateCodeIsEqualOrMoreThanMinimumDuplicateLines: SUCCESS 
ValidateDuplicateCodeStartLineIsCorrect: SUCCESS 
ValidateDuplicateCodeEndLineIsCorrect: SUCCESS 
ValidateThatDuplicateCodeShouldBeExtracted: SUCCESS 
ValidateOnlyRemovedLinesAreAddedIntoExtractedCodeWithSomeExceptions: SUCCESS 
ValidateAddedCodeHasCorrectAccessModifier: SUCCESS 
ValidateThatCallToExtractedMethodIsSameAtAllPlaces: FAILED 
<pre>Call to extracted method are not the same at all places: 
extractedMethod86986(configPage); // CAP AL
extractedMethod86986(htmlPage); // CAP AL</pre>
ValidateImportsAreCorrect: SUCCESS 
ValidateExtractedMethodIsInCorrectLocation: SUCCESS 
ValidateFilesModifiedInPrMatchesTheFileInJira: SUCCESS 
ValidateMethodParameterOnExtractedCodeIsProperlyUsed - : SUCCESS 
<pre>Parameters: configPage</pre>
ValidateMethodParameterAndArgumentsAreSame: SUCCESS 
ValidateThatDeletedLinesMatchesTheDuplicateCodesInJira: SUCCESS 
validateHandlingOfVariableAssignmentIsCorrect: FAILED 
<pre>Variable element is not updated
Variable element is not updated
Variable element is not updated
</pre>
ValidateThatAllDeletedLinesAreTheSameAtAllPlaces: FAILED 
<pre>Number of deleted lines are not the same on all instances</pre>
ValidateAddedCodeAreRelatedToDuplicateCodeFixing: SUCCESS 
ValidateVariablesUsedInsideExtractedCodeAreAccessible: SUCCESS 
ValidateMethodCanBeStatic: SUCCESS

**Comment by audalykh** [comment]
https://devgraph-alp.atlassian.net/browse/CC-139644
Automated QE Check Result: FAILED
ValidateAllDuplicateLinesAreExactlyTheSame: SUCCESS 
ValidateDuplicateCodeIsEqualOrMoreThanMinimumDuplicateLines: SUCCESS 
ValidateDuplicateCodeStartLineIsCorrect: SUCCESS 
ValidateDuplicateCodeEndLineIsCorrect: SUCCESS 
ValidateThatDuplicateCodeShouldBeExtracted: SUCCESS 
ValidateOnlyRemovedLinesAreAddedIntoExtractedCodeWithSomeExceptions: SUCCESS 
ValidateAddedCodeHasCorrectAccessModifier: SUCCESS 
ValidateThatCallToExtractedMethodIsSameAtAllPlaces: FAILED 
<pre>Call to extracted method are not the same at all places: 
extractedMethod86986(configPage); // CAP AL
extractedMethod86986(htmlPage); // CAP AL</pre>
ValidateImportsAreCorrect: SUCCESS 
ValidateExtractedMethodIsInCorrectLocation: SUCCESS 
ValidateFilesModifiedInPrMatchesTheFileInJira: SUCCESS 
ValidateMethodParameterOnExtractedCodeIsProperlyUsed - : SUCCESS 
<pre>Parameters: configPage</pre>
ValidateMethodParameterAndArgumentsAreSame: SUCCESS 
ValidateThatDeletedLinesMatchesTheDuplicateCodesInJira: SUCCESS 
validateHandlingOfVariableAssignmentIsCorrect: FAILED 
<pre>Variable element is not updated
Variable element is not updated
Variable element is not updated
</pre>
ValidateThatAllDeletedLinesAreTheSameAtAllPlaces: FAILED 
<pre>Number of deleted lines are not the same on all instances</pre>
ValidateAddedCodeAreRelatedToDuplicateCodeFixing: SUCCESS 
ValidateVariablesUsedInsideExtractedCodeAreAccessible: SUCCESS 
ValidateMethodCanBeStatic: SUCCESS

**Comment by audalykh** [comment]
https://devgraph-alp.atlassian.net/browse/CC-139644
Automated QE Check Result: FAILED
ValidateAllDuplicateLinesAreExactlyTheSame: SUCCESS 
ValidateDuplicateCodeIsEqualOrMoreThanMinimumDuplicateLines: SUCCESS 
ValidateDuplicateCodeStartLineIsCorrect: SUCCESS 
ValidateDuplicateCodeEndLineIsCorrect: SUCCESS 
ValidateThatDuplicateCodeShouldBeExtracted: SUCCESS 
ValidateOnlyRemovedLinesAreAddedIntoExtractedCodeWithSomeExceptions: SUCCESS 
ValidateAddedCodeHasCorrectAccessModifier: SUCCESS 
ValidateThatCallToExtractedMethodIsSameAtAllPlaces: FAILED 
<pre>Call to extracted method are not the same at all places: 
extractedMethod86986(configPage); // CAP AL
extractedMethod86986(htmlPage); // CAP AL</pre>
ValidateImportsAreCorrect: SUCCESS 
ValidateExtractedMethodIsInCorrectLocation: SUCCESS 
ValidateFilesModifiedInPrMatchesTheFileInJira: SUCCESS 
ValidateMethodParameterOnExtractedCodeIsProperlyUsed - : SUCCESS 
<pre>Parameters: configPage</pre>
ValidateMethodParameterAndArgumentsAreSame: SUCCESS 
ValidateThatDeletedLinesMatchesTheDuplicateCodesInJira: SUCCESS 
validateHandlingOfVariableAssignmentIsCorrect: FAILED 
<pre>Variable element is not updated
Variable element is not updated
Variable element is not updated
</pre>
ValidateThatAllDeletedLinesAreTheSameAtAllPlaces: FAILED 
<pre>Number of deleted lines are not the same on all instances</pre>
ValidateAddedCodeAreRelatedToDuplicateCodeFixing: SUCCESS 
ValidateVariablesUsedInsideExtractedCodeAreAccessible: SUCCESS 
ValidateMethodCanBeStatic: SUCCESS

**Comment by audalykh** [comment]
https://devgraph-alp.atlassian.net/browse/CC-139644
Automated QE Check Result: FAILED
ValidateAllDuplicateLinesAreExactlyTheSame: SUCCESS 
ValidateDuplicateCodeIsEqualOrMoreThanMinimumDuplicateLines: SUCCESS 
ValidateDuplicateCodeStartLineIsCorrect: SUCCESS 
ValidateDuplicateCodeEndLineIsCorrect: SUCCESS 
ValidateThatDuplicateCodeShouldBeExtracted: SUCCESS 
ValidateOnlyRemovedLinesAreAddedIntoExtractedCodeWithSomeExceptions: SUCCESS 
ValidateAddedCodeHasCorrectAccessModifier: SUCCESS 
ValidateThatCallToExtractedMethodIsSameAtAllPlaces: FAILED 
<pre>Call to extracted method are not the same at all places: 
extractedMethod86986(configPage); // CAP AL
extractedMethod86986(htmlPage); // CAP AL</pre>
ValidateImportsAreCorrect: SUCCESS 
ValidateExtractedMethodIsInCorrectLocation: SUCCESS 
ValidateFilesModifiedInPrMatchesTheFileInJira: SUCCESS 
ValidateMethodParameterOnExtractedCodeIsProperlyUsed - : SUCCESS 
<pre>Parameters: configPage</pre>
ValidateMethodParameterAndArgumentsAreSame: SUCCESS 
ValidateThatDeletedLinesMatchesTheDuplicateCodesInJira: SUCCESS 
validateHandlingOfVariableAssignmentIsCorrect: FAILED 
<pre>Variable element is not updated
Variable element is not updated
Variable element is not updated
</pre>
ValidateThatAllDeletedLinesAreTheSameAtAllPlaces: FAILED 
<pre>Number of deleted lines are not the same on all instances</pre>
ValidateAddedCodeAreRelatedToDuplicateCodeFixing: SUCCESS 
ValidateVariablesUsedInsideExtractedCodeAreAccessible: SUCCESS 
ValidateMethodCanBeStatic: SUCCESS

**Comment by audalykh** [comment]
https://devgraph-alp.atlassian.net/browse/CC-139644
Automated QE Check Result: FAILED
ValidateAllDuplicateLinesAreExactlyTheSame: SUCCESS 
ValidateDuplicateCodeIsEqualOrMoreThanMinimumDuplicateLines: SUCCESS 
ValidateDuplicateCodeStartLineIsCorrect: SUCCESS 
ValidateDuplicateCodeEndLineIsCorrect: SUCCESS 
ValidateThatDuplicateCodeShouldBeExtracted: SUCCESS 
ValidateOnlyRemovedLinesAreAddedIntoExtractedCodeWithSomeExceptions: SUCCESS 
ValidateAddedCodeHasCorrectAccessModifier: SUCCESS 
ValidateThatCallToExtractedMethodIsSameAtAllPlaces: FAILED 
<pre>Call to extracted method are not the same at all places: 
extractedMethod86986(configPage); // CAP AL
extractedMethod86986(htmlPage); // CAP AL</pre>
ValidateImportsAreCorrect: SUCCESS 
ValidateExtractedMethodIsInCorrectLocation: SUCCESS 
ValidateFilesModifiedInPrMatchesTheFileInJira: SUCCESS 
ValidateMethodParameterOnExtractedCodeIsProperlyUsed - : SUCCESS 
<pre>Parameters: configPage</pre>
ValidateMethodParameterAndArgumentsAreSame: SUCCESS 
ValidateThatDeletedLinesMatchesTheDuplicateCodesInJira: SUCCESS 
validateHandlingOfVariableAssignmentIsCorrect: FAILED 
<pre>Variable element is not updated
Variable element is not updated
Variable element is not updated
</pre>
ValidateThatAllDeletedLinesAreTheSameAtAllPlaces: FAILED 
<pre>Number of deleted lines are not the same on all instances</pre>
ValidateAddedCodeAreRelatedToDuplicateCodeFixing: SUCCESS 
ValidateVariablesUsedInsideExtractedCodeAreAccessible: SUCCESS 
ValidateMethodCanBeStatic: SUCCESS

**Comment by audalykh** [comment]
https://devgraph-alp.atlassian.net/browse/CC-139644
Automated QE Check Result: FAILED
ValidateAllDuplicateLinesAreExactlyTheSame: SUCCESS 
ValidateDuplicateCodeIsEqualOrMoreThanMinimumDuplicateLines: SUCCESS 
ValidateDuplicateCodeStartLineIsCorrect: SUCCESS 
ValidateDuplicateCodeEndLineIsCorrect: SUCCESS 
ValidateThatDuplicateCodeShouldBeExtracted: SUCCESS 
ValidateOnlyRemovedLinesAreAddedIntoExtractedCodeWithSomeExceptions: SUCCESS 
ValidateAddedCodeHasCorrectAccessModifier: SUCCESS 
ValidateThatCallToExtractedMethodIsSameAtAllPlaces: FAILED 
<pre>Call to extracted method are not the same at all places: 
extractedMethod86986(configPage); // CAP AL
extractedMethod86986(htmlPage); // CAP AL</pre>
ValidateImportsAreCorrect: SUCCESS 
ValidateExtractedMethodIsInCorrectLocation: SUCCESS 
ValidateFilesModifiedInPrMatchesTheFileInJira: SUCCESS 
ValidateMethodParameterOnExtractedCodeIsProperlyUsed - : SUCCESS 
<pre>Parameters: configPage</pre>
ValidateMethodParameterAndArgumentsAreSame: SUCCESS 
ValidateThatDeletedLinesMatchesTheDuplicateCodesInJira: SUCCESS 
validateHandlingOfVariableAssignmentIsCorrect: FAILED 
<pre>Variable element is not updated
Variable element is not updated
Variable element is not updated
</pre>
ValidateThatAllDeletedLinesAreTheSameAtAllPlaces: FAILED 
<pre>Number of deleted lines are not the same on all instances</pre>
ValidateAddedCodeAreRelatedToDuplicateCodeFixing: SUCCESS 
ValidateVariablesUsedInsideExtractedCodeAreAccessible: SUCCESS 
ValidateMethodCanBeStatic: SUCCESS

**Comment by audalykh** [comment]
https://devgraph-alp.atlassian.net/browse/CC-139644
Automated QE Check Result: FAILED
ValidateAllDuplicateLinesAreExactlyTheSame: SUCCESS 
ValidateDuplicateCodeIsEqualOrMoreThanMinimumDuplicateLines: SUCCESS 
ValidateDuplicateCodeStartLineIsCorrect: SUCCESS 
ValidateDuplicateCodeEndLineIsCorrect: SUCCESS 
ValidateThatDuplicateCodeShouldBeExtracted: SUCCESS 
ValidateOnlyRemovedLinesAreAddedIntoExtractedCodeWithSomeExceptions: SUCCESS 
ValidateAddedCodeHasCorrectAccessModifier: SUCCESS 
ValidateThatCallToExtractedMethodIsSameAtAllPlaces: FAILED 
<pre>Call to extracted method are not the same at all places: 
extractedMethod86986(configPage); // CAP AL
extractedMethod86986(htmlPage); // CAP AL</pre>
ValidateImportsAreCorrect: SUCCESS 
ValidateExtractedMethodIsInCorrectLocation: SUCCESS 
ValidateFilesModifiedInPrMatchesTheFileInJira: SUCCESS 
ValidateMethodParameterOnExtractedCodeIsProperlyUsed - : SUCCESS 
<pre>Parameters: configPage</pre>
ValidateMethodParameterAndArgumentsAreSame: SUCCESS 
ValidateThatDeletedLinesMatchesTheDuplicateCodesInJira: SUCCESS 
validateHandlingOfVariableAssignmentIsCorrect: FAILED 
<pre>Variable element is not updated
Variable element is not updated
Variable element is not updated
</pre>
ValidateThatAllDeletedLinesAreTheSameAtAllPlaces: FAILED 
<pre>Number of deleted lines are not the same on all instances</pre>
ValidateAddedCodeAreRelatedToDuplicateCodeFixing: SUCCESS 
ValidateVariablesUsedInsideExtractedCodeAreAccessible: SUCCESS 
ValidateMethodCanBeStatic: SUCCESS

**Pull request merged**
